/*
INTEGRAÇÃO (4.3) — O "Tutor IA" deixou de gerar texto localmente: a
recomendação vem do agente edubot_agent no backend (GET /edubot/recommendation),
que aplica as 6 regras pedagógicas sobre o perfil real e persiste o resultado
no histórico de intervenções (exibido ao lado).
*/
import { Bot, FileDown, LoaderCircle, Sparkles } from "lucide-react";
import { useState } from "react";
import { Recommendation, StudentProfile, getEdubotRecommendation } from "../services/api";
import { useT } from "../i18n";
import { EduBotLogo } from "./brand/EduBotLogo";

interface ReportProps {
  profile: StudentProfile;
  onTracked: () => void;
}

const priorityStyle: Record<string, string> = {
  alta: "bg-rose-50 text-rose-700",
  media: "bg-amber-50 text-amber-700",
  baixa: "bg-slate-100 text-slate-600"
};

export const Report = ({ profile, onTracked }: ReportProps) => {
  const t = useT();
  const [recommendation, setRecommendation] = useState<Recommendation | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ask = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await getEdubotRecommendation();
      setRecommendation(response.recommendation);
      onTracked(); // atualiza o histórico de intervenções no perfil
    } catch {
      setError(t("Não foi possível consultar o EduBot agora.", "Couldn't reach EduBot right now."));
    } finally {
      setLoading(false);
    }
  };

  const exportProfile = () => {
    const blob = new Blob([JSON.stringify(profile, null, 2)], { type: "application/json" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `perfil-${profile.estudante.ra}.json`;
    link.click();
    URL.revokeObjectURL(link.href);
  };

  return (
    <section className="grid gap-6 xl:grid-cols-[1fr_360px]">
      <div className="rounded-[8px] border border-line bg-white p-8 shadow-soft">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <EduBotLogo size={48} />
            <div>
              <h1 className="text-3xl font-bold text-ink">{t("Professor Mediador", "Mediating Professor")} — EduBot</h1>
              <p className="mt-1 text-muted">
                {t(
                  "Recomendação pedagógica gerada pelo agente a partir da sua jornada rastreada.",
                  "Pedagogical recommendation generated by the agent from your tracked journey."
                )}
              </p>
            </div>
          </div>
          <button
            onClick={ask}
            disabled={loading}
            className="flex h-12 items-center gap-2 rounded-[8px] bg-brand px-5 font-bold text-white disabled:bg-slate-300"
          >
            {loading ? <LoaderCircle className="animate-spin" size={20} /> : <Sparkles size={20} />}
            {t("Pedir recomendação", "Ask for a recommendation")}
          </button>
        </div>

        {error && <p className="mt-6 rounded-[8px] bg-rose-50 p-4 font-semibold text-rose-700">{error}</p>}

        {recommendation ? (
          <div className="mt-8 space-y-5">
            <div className="flex flex-wrap items-center gap-2">
              <span className="rounded-[8px] bg-indigo-50 px-3 py-2 text-sm font-bold text-indigo-800">
                {recommendation.tipo}
              </span>
              <span className={`rounded-[8px] px-3 py-2 text-sm font-bold ${priorityStyle[recommendation.prioridade]}`}>
                {t("prioridade", "priority")} {recommendation.prioridade}
              </span>
              {recommendation.mock && (
                <span className="rounded-[8px] bg-slate-100 px-3 py-2 text-xs font-semibold text-muted">
                  {t("resposta simulada — Bedrock ainda não conectado", "simulated response — Bedrock not connected yet")}
                </span>
              )}
            </div>

            <h2 className="text-2xl font-bold text-ink">{recommendation.titulo}</h2>
            <p className="rounded-[8px] bg-indigo-50/60 p-5 text-lg leading-8 text-slate-800">
              {recommendation.mensagem_aluno}
            </p>

            <div>
              <h3 className="font-bold text-ink">{t("Plano de ação", "Action plan")}</h3>
              <ul className="mt-3 space-y-2">
                {recommendation.acoes.map((acao) => (
                  <li key={acao} className="flex items-start gap-3 rounded-[8px] border border-line p-4">
                    <Bot className="mt-0.5 shrink-0 text-brand" size={20} />
                    <span className="text-slate-700">{acao}</span>
                  </li>
                ))}
              </ul>
            </div>

            <p className="text-sm text-muted">
              <strong>{t("Justificativa (para o professor):", "Rationale (for the teacher):")}</strong> {recommendation.justificativa}
            </p>
          </div>
        ) : (
          <div className="mt-10 flex flex-col items-center gap-4 rounded-[8px] bg-slate-50 p-10 text-center text-muted">
            <Bot size={48} className="text-brand" />
            <p className="max-w-md">
              {t(
                'Clique em "Pedir recomendação" para o EduBot analisar seu consumo de recursos, desempenho nos quizzes e competências, e sugerir o próximo passo.',
                'Click "Ask for a recommendation" for EduBot to analyze your resource consumption, quiz performance and competencies, and suggest the next step.'
              )}
            </p>
          </div>
        )}
      </div>

      <aside className="h-fit space-y-6">
        <div className="rounded-[8px] border border-line bg-white p-6">
          <h2 className="text-xl font-bold text-ink">{t("Histórico de intervenções", "Intervention history")}</h2>
          <div className="mt-4 space-y-3">
            {profile.historico_intervencoes.map((item, index) => (
              <div key={`${item.data}-${index}`} className="rounded-[8px] bg-slate-50 p-4">
                <div className="flex items-center justify-between text-xs text-muted">
                  <span className="font-bold uppercase tracking-wide">{item.tipo}</span>
                  <span>{item.data}</span>
                </div>
                <p className="mt-2 text-sm text-slate-700">{item.descricao}</p>
              </div>
            ))}
            {profile.historico_intervencoes.length === 0 && (
              <p className="text-sm text-muted">{t("Nenhuma intervenção registrada ainda.", "No interventions recorded yet.")}</p>
            )}
          </div>
        </div>

        <div className="rounded-[8px] border border-line bg-white p-6">
          <h2 className="text-xl font-bold text-ink">{t("Exportar dados", "Export data")}</h2>
          <p className="mt-2 text-sm text-muted">{t("Baixe o JSON com o seu perfil completo rastreado.", "Download the JSON with your full tracked profile.")}</p>
          <button
            onClick={exportProfile}
            className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-[8px] bg-ink font-semibold text-white"
          >
            <FileDown size={18} />
            {t("Exportar JSON", "Export JSON")}
          </button>
        </div>
      </aside>
    </section>
  );
};
